apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure
        image: anjali8329/medicure-patient-service:latest
        ports:
        - containerPort: 8080
